/*

 BIRDSPRITE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char Bird[] =
{
  0x00,0x1C,0x00,0x3E,0x04,0x7E,0x81,0x7F,
  0xF0,0x0E,0xE0,0x1C,0x00,0x7C,0x00,0x38
};

/* End of BIRDSPRITE.C */
